import { ERole } from '@common/constants/roles.enum';
import { EJobTitleId } from '@common/constants/jobtitle.enum';
import { EDepartmentId } from '@common/constants/department.enum';

export const usersSeedData = [
  {
    id: 'uuid-user-1',
    employeeCode: 'fh-0001',
    googleId: 'google-1234567890',
    email: 'john.doe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    nickName: 'Johnny',
    avatarUrl: 'https://example.com/avatar/john.jpg',
    birthDate: new Date('1990-05-15'),
    salary: 35000,
    roleId: ERole.EMPLOYEE,
    jobTitleId: EJobTitleId.DEPARTMENT_HEAD,
    departmentId: EDepartmentId.HR,
    approvedBy: null,
    approvedUsers: null,
    approvedAt: null,
  },
  {
    id: 'uuid-user-2',
    employeeCode: 'fh-0002',
    googleId: 'google-0987654321',
    email: 'jane.smith@example.com',
    firstName: 'Jane',
    lastName: 'Smith',
    nickName: 'Janey',
    avatarUrl: 'https://example.com/avatar/jane.jpg',
    birthDate: new Date('1988-11-22'),
    salary: 42000,
    roleId: ERole.ADMIN,
    jobTitleId: EJobTitleId.STAFF,
    departmentId: EDepartmentId.HR,
    approvedBy: null,
    approvedUsers: null,
    approvedAt: null,
  },
  {
    id: 'uuid-admin-1',
    employeeCode: 'fh-0003',
    googleId: 'google-1122334455',
    email: 'somsri.thaiprang@example.com',
    firstName: 'สมศรี',
    lastName: 'ไทยปราณี',
    nickName: 'สม',
    avatarUrl: '',
    birthDate: new Date('1995-02-10'),
    salary: 28000,
    roleId: ERole.EMPLOYEE,
    jobTitleId: EJobTitleId.STAFF,
    departmentId: EDepartmentId.IT,
    approvedBy: null,
    approvedUsers: null,
    approvedAt: null,
  }
];
