export enum JobTitleId {
    DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
    MANAGER = 'MANAGER',
    SUPERVISOR = 'SUPERVISOR',
    STAFF = 'STAFF',
    BACKEND_DEVELOPER = 'BACKEND_DEVELOPER',
    FRONTEND_DEVELOPER = 'FRONTEND_DEVELOPER',
    UIUX_DESIGNER = 'UIUX_DESIGNER',
    MARKETING_SPECIALIST = 'MARKETING_SPECIALIST',
    FINANCE_SPECIALIST = 'FINANCE_SPECIALIST',
    SALES_SPECIALIST = 'SALES_SPECIALIST',
    OTHER = "OTHER",
    DEPARTMENT_HEAD_TEST = 'DEPARTMENT_HEAD_TEST',
}