export const errorMessage = {
  '400': 'Bad request',
  '401': 'Unauthorized',
  '403': 'Forbidden',
  '404': 'Not found',
  '409': 'Conflict',
  '500': 'Internal server error',

  '0001': 'Department not found',
  '0002': 'Department name already exists',
  '0003': 'Department name must be between 2 and 100 characters',
  '0004': 'Cannot delete department that has users',
  '0005': 'Cannot delete department that has job titles',
  '0006': 'Invalid department ID',

  '0101': 'Job title not found',
  '0102': 'Job title name already exists',
  '0103': 'Job title name must be between 2 and 100 characters',
  '0104': 'Cannot delete job title that has users',
  '0105': 'Invalid job title ID',
  '0106': 'Cannot delete job title because there are users currently assigned to it',

  '0201': 'Holiday not found',
  '0202': 'Holiday name already exists',
  '0203': 'Holiday name must be between 2 and 100 characters',
  '0204': 'Cannot delete holiday that has users',
  '0205': 'Invalid holiday ID',
  '0206': 'Holiday dates overlap with existing holiday',
  '0207': 'Holiday start date must be before end date',
  '0208': 'Holiday end date must be after start date',
  '0209': 'Holiday total days must be between 1 and 365',
  '0210': 'Holiday start date must not be later than end date',
  '0211': 'Holiday total days must be at least 1 day',
  '0212': 'Holiday start date is required',
  '0213': 'Holiday start date is invalid',
  '0214': 'Holiday end date is invalid',
  '0215': 'Total days must be equal to the number of days between start and end dates',


  '0301': 'Leave Type not found',
  '0302': 'Leave Type name already exists',
  '0303': 'Leave Type name must be between 2 and 100 characters',
  '0304': 'Cannot delete leave type that has users',
  '0305': 'Invalid leave type ID',

  '0401': 'Leave not found',
  '0402': 'Leave name already exists',
  '0403': 'Leave name must be between 2 and 100 characters',
  '0404': 'Cannot delete leave that has users',
  '0405': 'Invalid leave ID',
  '0406': 'Start date must not be after end date',
  '0407': 'Leave dates overlap with an existing leave request',
  '0408': 'You are not authorized to update this leave',
  '0409': 'Leave status must be PENDING',

  '0501': 'Permission not found',
  '0502': 'Permission name already exists',
  '0503': 'Permission name must be between 2 and 100 characters',
  '0504': 'Cannot delete permission that has users',
  '0505': 'Invalid permission ID',

  '0601': 'Role not found',
  '0602': 'Role name already exists',
  '0603': 'Role name must be between 2 and 100 characters',
  '0604': 'Cannot delete role that has users',
  '0605': 'Invalid role ID',
  '0606': 'Role name is required and cannot be empty',

  '0701': 'User not found',
  '0702': 'User name already exists',
  '0703': 'User name must be between 2 and 100 characters',
  '0704': 'Cannot delete user that has users',
  '0705': 'Invalid user ID',
  '0706': 'Email already exists',
  '0707': 'Birth date is not valid',

  '0801': 'Facility Request not found',
  '0802': 'Facility Request name already exists',
  '0803': 'Facility Request name must be between 2 and 100 characters',
  '0804': 'Cannot delete facility request that has users',
  '0805': 'Invalid facility request ID',

  '0901': 'Item not found',
  '0902': 'Item name already exists',
  '0903': 'Item name must be between 2 and 100 characters',
  '0904': 'Cannot delete item that has users',
  '0905': 'Invalid item ID',

  '1001': 'Item Request not found',
  '1002': 'Item Request name already exists',
  '1003': 'Item Request name must be between 2 and 100 characters',
  '1004': 'Cannot delete item request that has users',
  '1005': 'Invalid item request ID',

  '1101': 'Item Request History not found',
  '1102': 'Item Request History name already exists',
  '1103': 'Item Request History name must be between 2 and 100 characters',
  '1104': 'Cannot delete item request history that has users',
  '1105': 'Invalid item request history ID',

};
