export enum EPermission {
    CREATE_DEPARTMENT = 'create_department',
    READ_DEPARTMENT = 'read_department',
    UPDATE_DEPARTMENT = 'update_department',
    DELETE_DEPARTMENT = 'delete_department',
    CREATE_JOB_TITLE = 'create_job_title',
    READ_JOB_TITLE = 'read_job_title',
    UPDATE_JOB_TITLE = 'update_job_title',
    DELETE_JOB_TITLE = 'delete_job_title',
    CREATE_USER = 'create_user',
    READ_USER = 'read_user',
    UPDATE_USER = 'update_user',
    DELETE_USER = 'delete_user',
    CREATE_ROLE = 'create_role',
    READ_ROLE = 'read_role',
    UPDATE_ROLE = 'update_role',
    DELETE_ROLE = 'delete_role',
    CREATE_PERMISSION = 'create_permission',
    READ_PERMISSION = 'read_permission',
    UPDATE_PERMISSION = 'update_permission',
    DELETE_PERMISSION = 'delete_permission',
}
